#!/bin/bash

#Intrucciones: cambie el grupo en que va a ejecutar, el nombre del trabajo para
#              identificarlo fácilmente, el número de núcleos máximo por nodo,
#              el número de procesos a utilizar, y la ruta donde está la lista de tareas.

# 1. Grupo en el que se va a ejecutar
#SBATCH --partition=C0

# 2. Nombre del trabajo. Puede cambiarlo 
# para identificarlo de forma más sencilla
#SBATCH --job-name="mri_optimization"

# 3. Numero máximo de tareas asignadas por nodo. 
#SBATCH --ntasks-per-node=2

# 4. Numero de procesos a ejecutar de forma simultanea (en total
# teniendo en cuenta a todos los nodos).
#SBATCH --ntasks=10

# 5. Archivo de log donde quedará lo que imprima su software por pantalla. 
#Lo recomendable es que el programa no imprima nada a pantalla, sino a fichero directamente
#SBATCH --output=/home/usurio/mri-p-optimization/results_vox.log
#SBATCH --error=/home/usurio/mri-p-optimization/error_vox.log

# 6. mem especifica la cantidad máxima de memoria que podrá utilizar en cada nodo. 
# El valor 0 indica que podrá utilizar toda la memoria.
#SBATCH --mem=0  

# 7. Si el proceso tarda más del tiempo especificado en time automaticamente se terminará, 
#lo que permitirá evitar que un proceso en el que hubo algún tipo de eror.
#El valor 0 indica que no se mata al proceso nunca, con lo que en caso
#de errores de ese tipo lo deberá terminar manualmente (con scancel)
#SBATCH --time=0 

# 8. En la línea siguiente cambie la ruta del fichero de tareas
Tasks=/home/usurio/mri-p-optimization/Tasks_vox.txt
mpirun.openmpi -np ${SLURM_NTASKS} /opt/ClusterTools/MPI_Scheduler $Tasks  1 

# Para enviarlo en la bash escriba sbatch nombreDeEsteFichero 
